### ISSUE TITLE
Review the image for the guide

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-rest-client-async#13]
@cajaygle can you help review the image to be published with this guide in the `assets` directory? Thank you.

**Comment by carrenelloyd** [comment]
Great, let me know how it looks in the build once you added it.

**Comment by evelinec** [comment]
@carrenelloyd can you send me a `png` file? Or you can push the file into the `assets` folder in this repo too. Thank you.

**Comment by evelinec** [comment]
Here's the refreshed draft site with the design image: https://draft-guides.mybluemix.net/guides/microprofile-rest-client-async.html

**Comment by carrenelloyd** [comment]
Here is the updated diagram with the following changes: 

"...squeeze the spaces between Kafka and Job, by bringing the two green bubbles up to align with Consume system status? Similarly for the Job and Service Gateway."

@evelinec We should set a max height/width this image is scaled to, or else it looks really blurry. If scaling is a must, then we should consider using an SVG and not a PNG. PNG images should never be scaled up or down.

![OpenLiberty_diagram](https://user-images.githubusercontent.com/53481064/64205378-ce51d900-ce65-11e9-8949-3a6d95fe68a7.png)

**Comment by yeekangc** [comment]
The additions of the user and the browser icon look good.  Thanks!

Then, usually, we don't do boxes for the operations between the services.  Can we simply have the words somehow instead of putting them in green boxes?

**Comment by carrenelloyd** [comment]
@yeekangc I don't suggest removing the green bubbles and not having the text contained in a bubble, the design will start to be compromised. @evelinec Suggested the "Consume job", "Publish job results", "Publish system status" span the width of all those arrows, without the container to span it will look like only the middle arrow "System 2" contains those actions. Perhaps discuss this further between the two of you to get on the same page if you want to make additional changes?

**Comment by evelinec** [comment]
Initially, the design had the 3 actions on the right hand, under `System N`, which isn't right. I'm good with spanning the 3 actions across all the arrows.

**Comment by yeekangc** [comment]
On 2nd thought, let us go with the latest that you have, @carrenelloyd, and consider what's more when we have additional feedback.'

Usually it's words on or besides the arrows without boxes.  One can check out "Collaboration Diagrams" for examples.

**Comment by evelinec** [comment]
Updated draft with the latest design: https://draft-guides.mybluemix.net/guides/microprofile-rest-client-async.html#what-youll-learn

**Comment by evelinec** [comment]
Clarified that the png image is no longer blurry because we're not using scaling for this image. Also checked with @carrenelloyd that she's not going to make further changes. Thank you. Closed.
