### ISSUE TITLE
Dev content review - 4

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-microprofile-rest-client-async#17]
- [x]  in readme, license year is `2019` instead of `2017, 2019`
- section "What you’ll learn"
  - [x] a bit odd only have 1 subsection "What is asynchronous programming?" and all long content. If use subsection, should it be more? Or remove the subsection and just bold the question
- Where to next?
  - [ ] add "Consuming RESTful services using the reactive JAX-RS client" guide

**Comment by evelinec** [comment]
The "Consuming RESTful services using the reactive JAX-RS client" guide is not published yet. We don't add draft guides to "where to next", do we? @gkwan-ibm

**Comment by gkwan-ibm** [comment]
If add ahead, any problem? Display incorrect info or no show? 

Or make an other issue as a reminder to update them after publish

**Comment by evelinec** [comment]
Yeah, I think it may display as empty box. Will open a separate issue as a reminder.

**Comment by evelinec** [comment]
Others are addressed in https://github.com/OpenLiberty/draft-guide-microprofile-rest-client-async/commit/9017a2748a092477eaf61ab0f1c4e4978f4ff315.
