### ISSUE TITLE
Nimrah's Feedback

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-microprofile-rest-client-async#20]
**Building and running the application**
- Make the url `http://localhost:8080/api/jobs/{jobId}` unclickable
- Make the `POST http://localhost:8080/api/jobs/` unclickable
- Move the sentence _"The services will take some time to become available."_ after the `./scripts/start-app` command and before the sentence "You can access the application by making requests to the gateway job endpoints."
- `Windows`,`Linux`,`Mac` should be all capitals (i.e. change `:win: Windows` to 
`:win: WINDOWS`, etc.)

**Running the tests**

- Error when running `mvn verify`

    > [ERROR] Failed to execute goal on project gateway: Could not resolve dependencies for project io.openliberty.guides:gateway:war:1.0-SNAPSHOT: Could not find artifact io.openliberty.guides:models:jar:1.0-SNAPSHOT

    - mvn version 3.6.1, jdk 11,

**Comment by evelinec** [comment]
> **Building and running the application**
> 

- [ ] Make the url `http://localhost:8080/api/jobs/{jobId}` unclickable

- [ ] Make the `POST http://localhost:8080/api/jobs/` unclickable

- [ ] Move the sentence _"The services will take some time to become available."_ after the `./scripts/start-app` command and before the sentence "You can access the application by making requests to the gateway job endpoints."

- [ ] `Windows`,`Linux`,`Mac` should be all capitals (i.e. change `:win: Windows` to `:win: WINDOWS`, etc.)

> **Running the tests**
> 

- [ ]  Error when running `mvn verify`

>   > [ERROR] Failed to execute goal on project gateway: Could not resolve dependencies for project io.openliberty.guides:gateway:war:1.0-SNAPSHOT: Could not find artifact io.openliberty.guides:models:jar:1.0-SNAPSHOT
>   
>   
>   
>   * mvn version 3.6.1, jdk 11,

**Comment by evelinec** [comment]
Fixed. @NimG98 can you review this issue and close when ready? Thanks.

**Comment by NimG98** [comment]
- Failure when running `mvn verify`

   ```
   -------------------------------------------------------
   [INFO]  T E S T S
   [INFO] -------------------------------------------------------
   [INFO] Running it.io.openliberty.guides.system.SystemEndpointTest
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
   [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 298.109 s <<< FAILURE! - in 
   it.io.openliberty.guides.system.SystemEndpointTest
   [ERROR] testRunJob(it.io.openliberty.guides.system.SystemEndpointTest)  Time elapsed: 221.16 s  
   <<< FAILURE!
   java.lang.AssertionError: No records processed
        at 
   it.io.openliberty.guides.system.SystemEndpointTest.testRunJob(SystemEndpointTest.java:155)

   [INFO] 
   [INFO] Results:
   [INFO] 
   [ERROR] Failures: 
   [ERROR]   SystemEndpointTest.testRunJob:155 No records processed
   [INFO] 
   [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
   ```

**Comment by NimG98** [comment]
Everything LGTM.
